// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj-aeXwugMiAc2pbxbz6pcSFCa9hQQbB4',
    appId: '1:892029209526:web:bc19a92cd817bd3074cf17',
    messagingSenderId: '892029209526',
    projectId: 'borrowbook-ebac9',
    authDomain: 'borrowbook-ebac9.firebaseapp.com',
    storageBucket: 'borrowbook-ebac9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwV2BZjIIO9Zc1o4BBLxeWFEVrWOPFTKU',
    appId: '1:892029209526:android:6d39d1eaa6de092c74cf17',
    messagingSenderId: '892029209526',
    projectId: 'borrowbook-ebac9',
    storageBucket: 'borrowbook-ebac9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCURsUR5XwmHyS3QVqNDa1NpCciJW01TdM',
    appId: '1:892029209526:ios:5b7f657cca43b53e74cf17',
    messagingSenderId: '892029209526',
    projectId: 'borrowbook-ebac9',
    storageBucket: 'borrowbook-ebac9.firebasestorage.app',
    iosBundleId: 'com.example.borrowbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCURsUR5XwmHyS3QVqNDa1NpCciJW01TdM',
    appId: '1:892029209526:ios:5b7f657cca43b53e74cf17',
    messagingSenderId: '892029209526',
    projectId: 'borrowbook-ebac9',
    storageBucket: 'borrowbook-ebac9.firebasestorage.app',
    iosBundleId: 'com.example.borrowbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj-aeXwugMiAc2pbxbz6pcSFCa9hQQbB4',
    appId: '1:892029209526:web:6b922c138bdfccef74cf17',
    messagingSenderId: '892029209526',
    projectId: 'borrowbook-ebac9',
    authDomain: 'borrowbook-ebac9.firebaseapp.com',
    storageBucket: 'borrowbook-ebac9.firebasestorage.app',
  );
}
